<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    
    <OutputType>WinExe</OutputType>
    <IsPackable>false</IsPackable>

    <Authors>Alex Stroot</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>Sandbox for ui testing wpf package features.</Description>
    <Copyright>2026</Copyright>
    <RepositoryUrl>https://github.com/AlexLexicon/Lexicom.Concentrate</RepositoryUrl>
    <RepositoryType>github</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lexicom.Mvvm.For.Wpf" Version="10.0.39" />
    <PackageReference Include="Lexicom.Validation.Amenities" Version="10.0.39" />
    <PackageReference Include="Lexicom.Validation.For.Wpf" Version="10.0.39" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lexicom.Concentrate.Wpf.Controls\Lexicom.Concentrate.Wpf.Controls.csproj" />
  </ItemGroup>

</Project>
