<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>lexicom.concentrate.nuget.icon.png</PackageIcon>

    <Authors>Alex Stroot</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>Adds convenient but optional features for any mvvm project. Although not necessary these features are specifically designed to integrate with other Lexicom mvvm packages.</Description>
    <Copyright>2026</Copyright>
    <PackageProjectUrl>https://github.com/AlexLexicon/Lexicom/tree/master/Lexicom.Concentrate.Mvvm.Amenities</PackageProjectUrl>
    <RepositoryUrl>https://github.com/AlexLexicon/Lexicom.Concentrate</RepositoryUrl>
    <RepositoryType>github</RepositoryType>
    <PackageTags>mvvm;dependencyinjection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="..\lexicom.concentrate.nuget.icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lexicom.Mvvm" Version="10.0.38" />
  </ItemGroup>

</Project>
